# Generated by Django 2.2.1 on 2019-05-10 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casos_de_exito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('caso_1', models.TextField(blank=True)),
                ('caso_2', models.TextField(blank=True)),
                ('caso_3', models.TextField(blank=True)),
                ('caso_4', models.TextField(blank=True)),
                ('caso_5', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, upload_to='casos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='como_comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('desc_general', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='contenedor_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='footer-img')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='energiaEvoluciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='experto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cargo', models.TextField()),
                ('descripcion', models.TextField()),
                ('link', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='fuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=60)),
                ('pro', models.TextField()),
                ('contra', models.TextField()),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='fuentes')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='hidraulico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='hidraulico')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='hidrocarburo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='hidrocarburo')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='historias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=60)),
                ('video', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='imagenes_fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('header', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_1', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_2', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_3', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_4', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_5', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_6', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_7', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_8', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_9', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_10', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_11', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_12', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_13', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_14', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_15', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_16', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_17', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_18', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_19', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_20', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_21', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_22', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_23', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_24', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_25', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_26', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_27', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_28', models.ImageField(blank=True, upload_to='fuentes')),
                ('footer', models.ImageField(blank=True, upload_to='fuentes')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_boton', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='imagesC3')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='minero_energetico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='minero')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='mitos_realidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('mito', models.CharField(max_length=200)),
                ('realidad_1', models.TextField(blank=True)),
                ('realidad_2', models.TextField(blank=True)),
                ('realidad_3', models.TextField(blank=True)),
                ('realidad_4', models.TextField(blank=True)),
                ('realidad_5', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=700)),
                ('link', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='noticia')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('noticia_principal', models.BooleanField()),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='para_comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_boton', models.CharField(max_length=120)),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='popup')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='redes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('link', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, upload_to='data')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='transicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.TextField()),
                ('titulo_resumen', models.CharField(max_length=60)),
                ('resumen', models.TextField()),
                ('texto_boton_1', models.CharField(max_length=60)),
                ('texto_boton_2', models.CharField(max_length=60)),
                ('texto_boton_3', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('link', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('link', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
