# Generated by Django 2.2.1 on 2019-05-10 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=700)),
                ('imagen', models.ImageField(blank=True, upload_to='gas')),
                ('subtitulo', models.CharField(blank=True, max_length=80)),
                ('subdescripcion', models.TextField(blank=True, max_length=700)),
                ('disponible', models.BooleanField()),
                ('link', models.TextField(blank=True)),
                ('nombre_boton', models.CharField(blank=True, max_length=80)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=700)),
                ('imagen', models.ImageField(blank=True, upload_to='reserva')),
                ('subtitulo', models.CharField(blank=True, max_length=80)),
                ('subdescripcion', models.TextField(blank=True, max_length=700)),
                ('disponible', models.BooleanField()),
                ('link', models.TextField(blank=True)),
                ('nombre_boton', models.CharField(blank=True, max_length=80)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
