# Generated by Django 2.1.5 on 2019-02-13 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contenedor_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=120)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='contenedor_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='expertos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('cargo', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='redes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='contenedor_1',
            name='titulo',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
