# Generated by Django 2.1.5 on 2019-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0002_auto_20190213_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertos',
            old_name='titulo',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='expertos',
            name='cargo',
        ),
        migrations.AddField(
            model_name='expertos',
            name='nombre',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
