# Generated by Django 2.1.5 on 2019-02-13 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0003_auto_20190213_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='experto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cargo', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='expertos',
        ),
    ]
