# Generated by Django 2.2.1 on 2019-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0003_infografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='infografia',
            name='nombre_boton1',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infografia',
            name='nombre_boton2',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infografia',
            name='upload',
            field=models.FileField(blank=True, upload_to='gas'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='descripcion',
            field=models.TextField(blank=True, max_length=6000),
        ),
        migrations.AlterField(
            model_name='gas',
            name='subdescripcion',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='gas',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='descripcion',
            field=models.TextField(blank=True, max_length=6000),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='subdescripcion',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
