# Generated by Django 2.1.5 on 2019-02-13 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0004_auto_20190213_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes_c3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_boton', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='imagesC3')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
