# Generated by Django 2.2.1 on 2019-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0004_auto_20190514_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='infografia',
            name='upload2',
            field=models.FileField(blank=True, upload_to='gas'),
        ),
    ]
