# Generated by Django 2.2.1 on 2019-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0005_infografia_upload2'),
    ]

    operations = [
        migrations.AddField(
            model_name='infografia',
            name='nombre_boton3',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
