# Generated by Django 2.1.5 on 2019-02-13 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0006_contenedor_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
