# Generated by Django 2.2.1 on 2019-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0006_infografia_nombre_boton3'),
    ]

    operations = [
        migrations.AddField(
            model_name='infografia',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='infografia'),
        ),
    ]
