# Generated by Django 2.2.1 on 2019-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0007_infografia_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='upload1',
            field=models.FileField(blank=True, upload_to='expertos'),
        ),
        migrations.AddField(
            model_name='experto',
            name='upload2',
            field=models.FileField(blank=True, upload_to='expertos'),
        ),
    ]
