# Generated by Django 2.1.5 on 2019-02-14 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0007_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=60)),
                ('pro', models.TextField()),
                ('contra', models.TextField()),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='fuentes')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
