# Generated by Django 2.1.5 on 2019-02-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0008_fuentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor_2',
            name='link',
            field=models.TextField(),
        ),
    ]
