# Generated by Django 2.2.1 on 2019-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0008_auto_20190516_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='nombre_boton1',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experto',
            name='nombre_boton2',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
