# Generated by Django 2.2.1 on 2019-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0009_auto_20190516_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experto',
            name='nombre_boton1',
        ),
        migrations.RemoveField(
            model_name='experto',
            name='nombre_boton2',
        ),
        migrations.RemoveField(
            model_name='experto',
            name='upload1',
        ),
        migrations.RemoveField(
            model_name='experto',
            name='upload2',
        ),
        migrations.AddField(
            model_name='comision',
            name='nombre_boton1',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='nombre_boton2',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='upload1',
            field=models.FileField(blank=True, upload_to='expertos'),
        ),
        migrations.AddField(
            model_name='comision',
            name='upload2',
            field=models.FileField(blank=True, upload_to='expertos'),
        ),
    ]
