# Generated by Django 2.1.5 on 2019-02-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0009_auto_20190213_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor_1',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagesC1'),
        ),
    ]
