# Generated by Django 2.1.5 on 2019-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0010_contenedor_1_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='experto',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
