# Generated by Django 2.1.5 on 2019-02-15 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0011_experto_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes_fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('header', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_1', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_2', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_3', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_4', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_5', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_6', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_7', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_8', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_9', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_10', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_11', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_12', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_13', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_14', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_15', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_16', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_17', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_18', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_19', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_20', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_21', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_22', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_23', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_24', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_25', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_26', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_27', models.ImageField(blank=True, upload_to='fuentes')),
                ('imagen_28', models.ImageField(blank=True, upload_to='fuentes')),
                ('footer', models.ImageField(blank=True, upload_to='fuentes')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
