# Generated by Django 2.2.4 on 2019-08-02 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0012_candidato_ciudad_interes_participar_previa_servidor_taller'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha_de_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=170)),
                ('ingreso_al_taller', models.BooleanField(blank=True, null=True)),
                ('salida_del_taller', models.BooleanField(blank=True, null=True)),
                ('taller_previo', models.BooleanField(blank=True, null=True)),
                ('entidad', models.CharField(blank=True, max_length=100)),
                ('candidato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='energias.candidato')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energias.interes')),
                ('participar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energias.participar')),
                ('servidor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='energias.servidor')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energias.taller')),
            ],
        ),
    ]
