# Generated by Django 2.1.5 on 2019-02-18 20:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0012_imagenes_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor_1',
            name='content',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
