# Generated by Django 2.1.5 on 2019-02-20 20:53

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0013_contenedor_1_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='energiaEvoluciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.TextField()),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagesC1')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_boton', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='imagesC3')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='transicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.TextField()),
                ('texto_boton_1', models.CharField(max_length=60)),
                ('texto_boton_2', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='contenedor_2',
            new_name='video',
        ),
        migrations.DeleteModel(
            name='contenedor_1',
        ),
        migrations.DeleteModel(
            name='contenedor_3',
        ),
        migrations.DeleteModel(
            name='imagenes_c3',
        ),
    ]
