# Generated by Django 2.2.4 on 2019-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0014_inscripcion_vocero_confirmaciona'),
    ]

    operations = [
        migrations.CreateModel(
            name='interes_voceroa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100)),
            ],
        ),
    ]
