# Generated by Django 2.1.5 on 2019-02-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0014_auto_20190220_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriz',
            name='texto',
        ),
        migrations.AddField(
            model_name='transicion',
            name='resumen',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
