# Generated by Django 2.2.4 on 2019-08-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0016_inscripcion_int_sectora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='int_sectora',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='energias.interes_voceroa'),
        ),
    ]
