# Generated by Django 2.2.4 on 2019-08-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0018_auto_20190806_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='int_sectora',
        ),
    ]
