# Generated by Django 2.2.4 on 2019-08-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0019_remove_inscripcion_int_sectora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energias.servidor'),
        ),
    ]
