# Generated by Django 2.1.5 on 2019-02-22 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0019_hidraulico'),
    ]

    operations = [
        migrations.CreateModel(
            name='hidrocarburo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='hidrocarburo')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='hidraulico',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='hidraulico'),
        ),
    ]
