# Generated by Django 2.1.5 on 2019-02-25 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0020_auto_20190222_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='mitos_realidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('mito', models.CharField(max_length=60)),
                ('realidad_1', models.TextField()),
                ('realidad_2', models.TextField()),
                ('realidad_3', models.TextField()),
                ('realidad_4', models.TextField()),
                ('realidad_5', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
