# Generated by Django 2.2.4 on 2019-08-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0020_auto_20190806_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='int_sectora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energias.interes_voceroa'),
        ),
    ]
