# Generated by Django 2.1.5 on 2019-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0022_como_comision_desc_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitos_realidad',
            name='mito',
            field=models.CharField(max_length=200),
        ),
    ]
