# Generated by Django 2.1.5 on 2019-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0023_auto_20190225_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitos_realidad',
            name='realidad_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mitos_realidad',
            name='realidad_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mitos_realidad',
            name='realidad_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mitos_realidad',
            name='realidad_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mitos_realidad',
            name='realidad_5',
            field=models.TextField(blank=True),
        ),
    ]
