# Generated by Django 2.2.4 on 2019-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0024_auto_20190806_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='cedula',
            field=models.BigIntegerField(unique=True),
        ),
    ]
