# Generated by Django 2.1.5 on 2019-02-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0024_auto_20190225_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='transicion',
            name='texto_boton_3',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
