# Generated by Django 2.2.4 on 2019-08-20 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0025_auto_20190816_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='formularioEmail2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=170)),
                ('fecha_de_creacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
