# Generated by Django 2.2.4 on 2019-10-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0026_formularioemail2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='int_sectora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energias.interes_voceroa'),
            preserve_default=False,
        ),
    ]
