# Generated by Django 2.1.5 on 2019-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0026_subasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='upload',
            field=models.FileField(blank=True, upload_to='data'),
        ),
    ]
