# Generated by Django 2.1.5 on 2019-02-26 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0027_subasta_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='casos_de_exito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('caso_1', models.TextField(blank=True)),
                ('caso_2', models.TextField(blank=True)),
                ('caso_3', models.TextField(blank=True)),
                ('caso_4', models.TextField(blank=True)),
                ('caso_5', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, upload_to='casos')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='subasta',
            name='upload',
            field=models.FileField(blank=True, upload_to='subasta'),
        ),
    ]
