# Generated by Django 2.2.4 on 2019-11-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0027_auto_20191004_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energias.candidato'),
        ),
    ]
