# Generated by Django 2.1.5 on 2019-02-27 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0028_auto_20190226_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='noticia')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='subasta',
            name='upload',
            field=models.FileField(blank=True, upload_to='data'),
        ),
    ]
