# Generated by Django 2.1.5 on 2019-03-01 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0029_auto_20190227_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_boton', models.CharField(max_length=120)),
                ('link', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='popup')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
