# Generated by Django 2.1.5 on 2019-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0031_remove_energiaevoluciona_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energiaevoluciona',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
