# Generated by Django 2.1.5 on 2019-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0034_auto_20190305_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
