# Generated by Django 2.1.5 on 2019-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0036_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='noticia_principal',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
