# Generated by Django 2.1.5 on 2019-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energias', '0038_historias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historias',
            name='imagen',
        ),
        migrations.AddField(
            model_name='historias',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
